### ISSUE TITLE
Evaluation results

### ISSUE THREAD

**Issue by julyiii** [jkpark0825/EANet#3]
Hi, Is there any thing needed to be modify in code  to get results in paper? It gets bad results when use gived checkpoints as following.
MPVPE for all hand sequences: 35.70 mm
MPVPE for single hand sequences: 35.29 mm
MPVPE for interacting hand sequences: 36.40 mm
MPJPE for all hand sequences: 32.16 mm
MPJPE for single hand sequences: 32.56 mm
MPJPE for interacting hand sequences: 31.75 mm

**Comment by jkpark0825** [comment]
Sorry for any confusion. I'll imediately check the code after the
conference.

2023년 10월 6일 금요일, julyiii ***@***.***>님이 작성:

**Comment by julyiii** [comment]
Sorry，I encountered this problem beause the environment goes wrong ,I have already resolved it . Thank you for your reply!
