### ISSUE TITLE
./data/InterHand26M/J_regressor_ih26m_mano.npy

### ISSUE THREAD

**Issue by aragakiyui611** [jkpark0825/EANet#4]
I cannot find this file, could you provide it? Thank you!

**Comment by jkpark0825** [comment]
Please refer to https://github.com/facebookresearch/InterHand2.6M to get the J_regressor_ih26m_mano.npy file.
Thank you.

**Comment by xungeer29** [comment]
> I cannot find this file

I cannot find J_regressor_ih26m_mano.npy in  https://github.com/facebookresearch/InterHand2.6M

**Comment by xungeer29** [comment]
> > I cannot find this file
> 
> I cannot find J_regressor_ih26m_mano.npy in https://github.com/facebookresearch/InterHand2.6M

Is this it ?
https://github.com/facebookresearch/InterHand2.6M/blob/main/tool/MANO_world_to_camera/J_regressor_mano_ih26m.npy

But raise new error: 
FileNotFoundError: [Errno 2] No such file or directory: '../data/InterHand26M/annotations/train/InterHand2.6M_train_data_hm.json'

**Comment by tym7777** [comment]
> > > I cannot find this file
> > 
> > 
> > I cannot find J_regressor_ih26m_mano.npy in https://github.com/facebookresearch/InterHand2.6M
> 
> Is this it ? https://github.com/facebookresearch/InterHand2.6M/blob/main/tool/MANO_world_to_camera/J_regressor_mano_ih26m.npy
> 
> But raise new error: FileNotFoundError: [Errno 2] No such file or directory: '../data/InterHand26M/annotations/train/InterHand2.6M_train_data_hm.json'

hey bro！have you find the file  '../data/InterHand26M/annotations/train/InterHand2.6M_train_data_hm.json' ？I have the same question with you.

**Comment by xungeer29** [comment]
> > > > I cannot find this file
> > > 
> > > 
> > > I cannot find J_regressor_ih26m_mano.npy in https://github.com/facebookresearch/InterHand2.6M
> > 
> > 
> > Is this it ? https://github.com/facebookresearch/InterHand2.6M/blob/main/tool/MANO_world_to_camera/J_regressor_mano_ih26m.npy
> > But raise new error: FileNotFoundError: [Errno 2] No such file or directory: '../data/InterHand26M/annotations/train/InterHand2.6M_train_data_hm.json'
> 
> hey bro！have you find the file '../data/InterHand26M/annotations/train/InterHand2.6M_train_data_hm.json' ？I have the same question with you.

No, not found

**Comment by aragakiyui611** [comment]
This `InterHand2.6M_train_data_hm.json` is exactly the `InterHand2.6M_train_data.json`. You could just change the name in the InterHand26M.py
